#!/bin/bash

#this script installs:
#snapd
#qemu agent
#docker
#cockpit

#update the system, install dnf utilities, epel repo
sudo dnf check-update
sudo dnf install dnf-utils
sudo dnf install epel-release
sudo dnf upgrade

#snapd, enable snapd socket, then create a symlink to enable classic Snap support
sudo dnf install snapd
sudo snap install core
sudo systemctl enable --now snapd.socket
sudo ln -s /var/lib/snapd/snap /snap


# Install and enable QEMU guest agent
sudo dnf install qemu-guest-agent -y
sudo systemctl start qemu-guest-agent
sudo systemctl enable qemu-guest-agent

# Install and enable Cockpit
sudo dnf install cockpit -y
sudo systemctl start cockpit
sudo systemctl enable cockpit

# Install and enable Docker Engine
sudo dnf check-update -y
sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo dnf install docker-ce docker-ce-cli containerd.io -y
sudo systemctl start docker
sudo systemctl enable docker

# Add the current user to the docker group
sudo usermod -aG docker $(whoami) 
newgrp docker



